title:               Patient Data Manager
url:                 https://patient-data-manager.github.io/pdm-website/
baseurl:             "/pdm-website"

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              GoInvo
  url:               https://github.com/goinvo
  email:             pdm@goinvo.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist